### ISSUE TITLE
I can't find a link to the windows GUI wallet 

### ISSUE THREAD

**Issue by auroracoin** [xelis-project/xelis-genesix-wallet#2]
I can't find a link to the windows GUI wallet

**Comment by g45t345rt** [comment]
https://github.com/xelis-project/xelis-genesix-wallet/releases/tag/0.0.2

**Comment by auroracoin** [comment]
I thought it would be a Qt

**Comment by g45t345rt** [comment]
Qt?

**Comment by auroracoin** [comment]
> Qt?

Yes a Qt gui wallet

**Comment by Ez3kiel-dev** [comment]
Hi, 
we don't use c++ and Qt, but Dart with Flutter framework.
you'll find the Windows executable in the link above.
