### ISSUE TITLE
MacOS 0.0.5 app broken

### ISSUE THREAD

**Issue by levanid** [xelis-project/xelis-genesix-wallet#7]
New version for Mac seems to be broken and doesn't extract properly as an app

Previous 0.0.4 version name is genesix-macos.app.zip and it extracts properly as an app
Current 0.0.5 version has name genesix-macos.zip and extracts as a folder with app internals

Could you please reupload it properly?

Thank you

**Comment by smolpuff** [comment]
Any updates? I cannot extract it either, still

**Comment by g45t345rt** [comment]
Sorry for the delay. 

This should be correctly packaged in the latest release.
https://github.com/xelis-project/xelis-genesix-wallet/releases/tag/0.0.6
