### ISSUE TITLE
MacOS app 0.0.6 broken

### ISSUE THREAD

**Issue by levanid** [xelis-project/xelis-genesix-wallet#8]
Just got a new update 0.0.6 as previous thread was closed https://github.com/xelis-project/xelis-genesix-wallet/issues/7

The new app cannot be opened on MacOS Sequoia 15.0.1

I got two windows saying "The application “genesix.app” can’t be opened."

**Comment by Slixe** [comment]
Hi @levanid did you give the permission in your settings to open the app?

**Comment by Ez3kiel-dev** [comment]
Hello @levanid,

I have updated the binary for macOS, can you try again ?
You will surely see this message: `Alert that Apple cannot check the app for malicious software`.
As we don't yet have an Apple Developer account to be notarized, follow the instructions [here](https://support.apple.com/en-us/102445) to use Genesix.

Keep us informed, thanks :)
