### ISSUE TITLE
AnyhowException when sending Xelis

### ISSUE THREAD

**Issue by sinovcm** [xelis-project/xelis-genesix-wallet#9]
Hi
I try to send some Xelis from my wallet and I keep getting following error
![Error](https://github.com/user-attachments/assets/8a85ccf0-32a9-423b-8fbd-9becb83a80e3)

**Comment by Gordonhills** [comment]
Hello @sinovcm 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID XEL07638
Please see the link below to our dedicated support line:
[Xelis Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Slixe** [comment]
hey @sinovcm could you try to send a bit less to see if its a problem with the fees? Thank you

**Comment by sinovcm** [comment]
Thanks @Slixe, you were right!
